### ISSUE TITLE
Pet names do not reflect updates to names

### ISSUE THREAD

**Issue by ntietz** [cthulahoops/rocket#23]
I noticed that if you change your name, the pet's name still reflects the old one. So if you change your name from X to Y, then Y will be followed around by animals like "X's penguin". This name was also used in chat, so the old name gets propagated when abandoning said pets.

I'm not sure what the right solution here is. I guess one could be to poll periodically for the names and update correspondingly.

**Comment by cthulahoops** [comment]
Thank you!

Yeah, this is a bit tricky - but I think I can do something that mostly works. So long as the pet server doesn't restart then the next time there's an event related to a user I can update all the pet names. So, if the user is active on Virtual RC there's no problem, I can update the pets.

The problem is that if user doesn't visit Virtual RC before the pet server restarts then on restart the pets won't recognise their owner. (There's a related problem if we have two Recursers with the same name.) This is just a limitation of the design, and I'd need to add server state to fix it.

I don't think polling helps, because I don't think the API tells us anything about offline users.

Have all the pets been abandoned already, or are there any I should rename manually? (Due to a quirk of Virtual RC, the abandonment message is only visible to anyone who's online at the time, anyone who joins later can't see it because the sender no longer exists.)

**Comment by ntietz** [comment]
Ahh sorry for the faulty suggestion of polling! That’s what I get for guessing without understanding the code haha. 

Thanks for looking into this!

I already abandoned the old pets, on a lookout for a new penguin and crab haha.

**Comment by cthulahoops** [comment]
Looking into code it looks like it's better than I remembered! Ownership is tracked based on `bot_json["message"]["mentioned_entity_ids"][0]`, so there's no trouble tracking owners across name changes and restarts! It still won't update until the next time the owner visits Virtual RC, but that's not too bad I think.

I hope the genie is kind to you!

**Comment by cthulahoops** [comment]
Okay, this should work. Now, I wonder if there's any way to try it without changing my name! :grimacing: 

Do you know how long name changes take to propagate through? Can I reasonably change my name on RC and back again without confusing too many people?

**Comment by ntietz** [comment]
I’m not sure! I think it was pretty near instantaneous for me. If you want a minimally confusing name change, putting an extra “l” in your last name may be not really noticed.

**Comment by cthulahoops** [comment]
Good suggestion! Though, I do feel there's some sort of "testing is my middle name" joke to made. :grinning: 

Have handled some more edge cases, and think I'm ready to go live with this. Thank you for the bug report, and sorry about the bad name handling.
