### ISSUE TITLE
Rocket bot strikes twice.

### ISSUE THREAD

**Issue by dl-watson** [cthulahoops/rocket#5]
Today, Nicholas was mowed down by an errant deer and exploded (as of writing, the evidence of impact remains on the floor in the Pet Adoption Agency and by his desk). 

This morning, I myself was both set on fire and aggressively thanked.

I'm not sure precisely when the second strike happens, but it's long enough after the first for one to let their guard down.

**Comment by cthulahoops** [comment]
When the script gets disconnected and reconnects to the API it picks up the content of the note again and sends a second rocket at the same target. It could fix it with timestamps, but it's quite fun to know that extra rockets could happen at any time.

You can work around the problem by just making sure Nicholas's name is in the note at all times so they get set on fire and thanked instead of you. :grin:
